# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ccntNE9IuzTp_GSWtCeQ8ByJBQD5zENO
"""

Height=float(input("請輸入您的身高(公尺):"))
Weight=float(input("請輸入您的體重(公斤):"))
BMI=Weight/(Height**2)
print(f"您的BMI值為:{BMI:.2f}")